<a href="https://colab.research.google.com/github/eliascruzdba/Enem_2019/blob/main/001_ML_ENEM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importação / Divisão Atributos previsores

In [3]:
import matplotlib
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import warnings
warnings.filterwarnings('ignore')
from sklearn import metrics

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [5]:
colunas = ['NU_INSCRICAO','SG_UF_RESIDENCIA', 'NU_NOTA_MT', 'NU_NOTA_REDACAO', 'Q001', 'Q002', 'Q005','Q006', 'NU_IDADE' ]

In [6]:
microdadosEnem = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Dataframe/df_ENEM_2019.csv", sep=';', encoding='ISO-8859-1', usecols=colunas)

In [9]:
microdadosEnem = microdadosEnem.dropna()

In [10]:
microdadosEnem.isna().sum()

NU_INSCRICAO        0
SG_UF_RESIDENCIA    0
NU_IDADE            0
NU_NOTA_MT          0
NU_NOTA_REDACAO     0
Q001                0
Q002                0
Q005                0
Q006                0
dtype: int64

In [14]:
y_Enem_MT = microdadosEnem.iloc[:,3].values

In [15]:
y_Enem_MT

array([392. , 677. , 675.3, ..., 390.7, 498.3, 389.5])

In [16]:
y_Enem_RD = microdadosEnem.iloc[:,4].values

In [17]:
y_Enem_RD

array([460., 860., 800., ..., 460., 540., 280.])

In [18]:
X_Enem = microdadosEnem

In [19]:
del X_Enem['NU_INSCRICAO']
del X_Enem['NU_NOTA_MT']
del X_Enem['NU_NOTA_REDACAO']

In [20]:
X_Enem

SG_UF_RESIDENCIA  NU_IDADE Q001 Q002  Q005 Q006
3                     TO      25.0    C    E     4    E
4                     MG      22.0    E    E     3    G
5                     MT      37.0    B    B     7    E
6                     BA      22.0    E    B     3    B
9                     SP      17.0    E    E     5    F
...                  ...       ...  ...  ...   ...  ...
5095257               MT      20.0    B    E     6    G
5095259               PI      37.0    A    A     4    C
5095260               SP      17.0    E    E     3    B
5095263               PA      33.0    H    E     3    E
5095264               SP      17.0    H    E     3    D

[3701947 rows x 6 columns]

# Label Encoder New

In [21]:
from sklearn.preprocessing import LabelEncoder

In [23]:
label_encoder_MT = LabelEncoder()
y_Enem_MT[:] = label_encoder_MT.fit_transform(y_Enem_MT[:])

In [24]:
X_Enem.columns

Index(['SG_UF_RESIDENCIA', 'NU_IDADE', 'Q001', 'Q002', 'Q005', 'Q006'], dtype='object')

In [25]:
X_Enem = X_Enem.iloc[:,:].values

In [26]:
label_encoder_SG_UF_RESIDENCIA = LabelEncoder()
label_encoder_Q001 = LabelEncoder()
label_encoder_Q002 = LabelEncoder()
label_encoder_Q006 = LabelEncoder()

In [27]:
X_Enem[:,0] = label_encoder_SG_UF_RESIDENCIA.fit_transform(X_Enem[:,0])
X_Enem[:,2] = label_encoder_Q001.fit_transform(X_Enem[:,2])
X_Enem[:,3] = label_encoder_Q002.fit_transform(X_Enem[:,3])
X_Enem[:,5] = label_encoder_Q006.fit_transform(X_Enem[:,5])

In [28]:
X_Enem[0]

array([26, 25.0, 2, 4, 4, 4], dtype=object)

# Gerar / Salvar Modelos de Treinamento

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
X_Enem_treinamento_MT, X_Enem_teste_MT, y_Enem_treinamento_MT, y_Enem_teste_MT = train_test_split(X_Enem, y_Enem_MT, test_size = 0.15, random_state = 0)
X_Enem_treinamento_RD, X_Enem_teste_RD, y_Enem_treinamento_RD, y_Enem_teste_RD = train_test_split(X_Enem, y_Enem_RD, test_size = 0.15, random_state = 0)

In [31]:
import pickle

In [32]:
with open('/content/drive/MyDrive/Colab Notebooks/Dataframe/Enem_MT.pkl', mode = 'wb') as f:
  pickle.dump([X_Enem_treinamento_MT, X_Enem_teste_MT, y_Enem_treinamento_MT, y_Enem_teste_MT], f)

In [33]:
with open('/content/drive/MyDrive/Colab Notebooks/Dataframe/Enem_RD.pkl', mode = 'wb') as f:
  pickle.dump([X_Enem_treinamento_RD, X_Enem_teste_RD, y_Enem_treinamento_RD, y_Enem_teste_RD], f)

In [34]:
X_Enem_treinamento_MT

array([[11, 16.0, 4, 5, 4, 8],
       [17, 17.0, 3, 4, 3, 6],
       [4, 20.0, 4, 3, 6, 1],
       ...,
       [22, 18.0, 1, 4, 4, 3],
       [8, 26.0, 4, 5, 5, 11],
       [8, 41.0, 6, 4, 4, 3]], dtype=object)

# Regressão Linear Multipla


In [36]:
from sklearn.linear_model import LinearRegression
regressor_multiplo_Enem = LinearRegression()
regressor_multiplo_Enem.fit(X_Enem_treinamento_MT, y_Enem_treinamento_MT)

LinearRegression()

In [37]:
regressor_multiplo_Enem.intercept_

1337.7242269755031

In [38]:
regressor_multiplo_Enem.coef_

array([  2.98493837, -10.88056098,  18.80776485,  54.88529438,
       -58.04235888, 125.7690599 ])

In [39]:
len(regressor_multiplo_Enem.coef_)

6

In [40]:
regressor_multiplo_Enem.score(X_Enem_treinamento_MT, y_Enem_treinamento_MT)

0.23979462132860407

In [41]:
regressor_multiplo_Enem.score(X_Enem_teste_MT, y_Enem_teste_MT)

0.23982480617664925

In [42]:
previsoes = regressor_multiplo_Enem.predict(X_Enem_teste_MT)
previsoes

array([2312.68226514, 2240.47879365, 1676.51228315, ..., 1331.51240911,
       1106.1274762 , 1876.17055992])

In [43]:
y_Enem_MT

array([ 331., 3181., 3164., ...,  318., 1394.,  306.])

In [45]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_Enem_teste_MT, previsoes)

768.668680484005

In [47]:
microdadosEnem, y_Enem_MT

(        SG_UF_RESIDENCIA  NU_IDADE Q001 Q002  Q005 Q006
 3                     TO      25.0    C    E     4    E
 4                     MG      22.0    E    E     3    G
 5                     MT      37.0    B    B     7    E
 6                     BA      22.0    E    B     3    B
 9                     SP      17.0    E    E     5    F
 ...                  ...       ...  ...  ...   ...  ...
 5095257               MT      20.0    B    E     6    G
 5095259               PI      37.0    A    A     4    C
 5095260               SP      17.0    E    E     3    B
 5095263               PA      33.0    H    E     3    E
 5095264               SP      17.0    H    E     3    D
 
 [3701947 rows x 6 columns],
 array([ 331., 3181., 3164., ...,  318., 1394.,  306.]))

In [48]:
type(y_Enem_MT)

numpy.ndarray

In [54]:
X_Enem_MT = microdadosEnem.iloc[:,1].values

In [55]:
type(X_Enem_MT)

numpy.ndarray

In [56]:
np.corrcoef(X_Enem_MT,y_Enem_MT)

array([[ 1.        , -0.13926875],
       [-0.13926875,  1.        ]])